botToken: 5423205939:AAFNaz5kIqN9InK1C9QwshAnyXLM9WFc6v8

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/driverHub
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  kafka:
    bootstrap_servers: localhost:9092
    my_topic: driverhub_topic
    consumer:
      group-id: driverhub_group_id
      auto_offset_reset: latest
      value_deserializer: "org.springframework.kafka.support.serializer.JsonDeserializer"
      properties:
        spring.json.trusted.packages: "*"
    producer:
      value_serializer: "org.springframework.kafka.support.serializer.JsonSerializer"

